/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Config: typeof import('./src/components/Config/index.vue')['default']
    Control: typeof import('./src/components/Control/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileSelect: typeof import('./src/components/FileSelect/index.vue')['default']
    ImageList: typeof import('./src/components/Source/ImageTab/ImageList.vue')['default']
    ImageTab: typeof import('./src/components/Source/ImageTab/index.vue')['default']
    Info: typeof import('./src/components/Info/index.vue')['default']
    Preview: typeof import('./src/components/Preview/index.vue')['default']
    Source: typeof import('./src/components/Source/index.vue')['default']
    Track: typeof import('./src/components/Track/index.vue')['default']
    VideoList: typeof import('./src/components/Source/VideoTab/VideoList.vue')['default']
    VideoTab: typeof import('./src/components/Source/VideoTab/index.vue')['default']
  }
}
